apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- frontend/deployment.yaml
- frontend/service.yaml
- api/deployment.yaml
- api/service.yaml
- auth/deployment.yaml
- auth/service.yaml
- files/deployment.yaml
- files/service.yaml
- postgres/statefulset.yaml
- postgres/service.yaml
- postgres/pvc.yaml
- redis/deployment.yaml
- redis/service.yaml
- minio/deployment.yaml
- minio/service.yaml
- minio/pvc.yaml
- ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: 4chan-v2

configMapGenerator:
- name: app-config
  literals:
  - API_PREFIX=api
  - API_VERSION=v1
  - CORS_ORIGINS=https://4chan-v2.example.com

secretsGenerator:
- name: database-credentials
  literals:
  - POSTGRES_USER=app_user
  - POSTGRES_PASSWORD=change_me_in_production
  - POSTGRES_DB=4chan